# Generated by Django 2.2.6 on 2020-04-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
